kind: pipeline
name: default

steps:
- name: test
  image: gradle:jdk8
  commands:
  - export GRADLE_USER_HOME=/drone/.gradle
  - env
  - pwd
  - whoami
  - touch $GRADLE_USER_HOME/foo.txt
  - gradle check