kind: pipeline
name: default

services:
- name: neo4j
  image: neo4j
  environment:
    NEO4J_AUTH: "none"
    NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

steps:
- name: build
  image: openjdk:8
  commands:
  - env
  - pwd
  - whoami
  - ./gradlew check