#!/bin/bash


cd ~

NEO4J_VERSION="3.4.7"
curl --silent http://dist.neo4j.org/neo4j-community-${NEO4J_VERSION}-unix.tar.gz -o /tmp/neo4j.tgz

tar zxf /tmp/neo4j.tgz || exit 1

rm -f /tmp/neo4j.tgz

cd ~/neo4j-community-${NEO4J_VERSION}
NEO4J_HOME=$(pwd)
echo $NEO4J_HOME

echo NEO4J_HOME=$NEO4J_HOME

cat <<EOF >>${NEO4J_HOME}/conf/neo4j.conf

dbms.security.auth_enabled=false

EOF

${NEO4J_HOME}/bin/neo4j start

export COUNTER=0
NEO4J_STATUS=1
while [ "$NEO4J_STATUS" -ne 0 ]; do
    sleep 5
    echo "Waiting for neo4j to finish starting..."
    curl http://localhost:7474 >/dev/null 2>&1
    NEO4J_STATUS=$?

    if [ "${COUNTER}" -gt 12 ]; then
        echo "Timed out waiting for neo4j"
        exit 99
    fi

    COUNTER=$(( ${COUNTER} + 1 ))
done

echo "Neo4j ready!!!"
echo

