#!/bin/bash


docker build . -t rebar-graph-kubernetes --build-arg GIT_COMMIT=$(git log -1 --format=%h) --build-arg GIT_REPO=$(git remote get-url origin)
docker tag rebar-graph-kubernetes rebar/rebar-graph-kubernetes
