#!/bin/bash


DOCKER_SRC_TAG=src-${CIRCLE_SHA1}

build_image() {
    docker build rebar-scanner-$1 \
    -t rebar/$1-scanner \
    -t rebar/$1-scanner:${DOCKER_SRC_TAG} \
    --build-arg CI_BUILD_URL=${CIRCLE_BUILD_URL} \
    --build-arg GIT_COMMIT=${CIRCLE_SHA1} \
    --build-arg GIT_REPO=${CIRCLE_REPOSITORY_URL} || exit 99
}

push_image() {
    docker push rebar/$1-scanner || exit 99
    docker push rebar/$1-scanner:${DOCKER_SRC_TAG} || exit 99
}

# build the shared base image
# this speeds multiple image builds, allows for shared layers, and minimizes duplication
docker build rebar-scanner-core -t rebar/scanner-core:latest

build_image docker
build_image kubernetes
build_image aws
build_image alibaba
build_iamge github

docker build rebar-dashboard -t rebar/rebar-dashboard \
    -t rebar/rebar-dashboard:${DOCKER_SRC_TAG} \
    --build-arg CI_BUILD_URL=${CIRCLE_BUILD_URL} \
    --build-arg GIT_COMMIT=${CIRCLE_SHA1} \
    --build-arg GIT_REPO=${CIRCLE_REPOSITORY_URL} || exit 99


if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
    echo "branch $CIRCLE_BRANCH is not master ... will not publish images"
    exit 0
fi

if [ ! "${DOCKER_PASSWORD}" = "" ]; then
    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
fi

docker push rebar/scanner-core:latest
push_image docker
push_image kubernetes
push_image aws
push_image alibaba
push_image github
docker push rebar/rebar-dashboard || exit 99
docker push rebar/rebar-dashboard:${DOCKER_SRC_TAG} || exit 99

docker logout 



