#!/bin/bash

if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
    echo "branch $CIRCLE_BRANCH is not master ... will not build image"
    exit 0
fi

if [ ! "${DOCKER_PASSWORD}" = "" ]; then
    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
fi

docker build rebar-graph-kubernetes -t rebar/rebar-graph-kubernetes --build-arg CI_BUILD_URL=${CIRCLE_BUILD_URL} --build-arg GIT_COMMIT=${CIRCLE_SHA1} --build-arg GIT_REPO=${CIRCLE_REPOSITORY_URL} || exit 99
docker build rebar-graph-aws -t rebar/rebar-graph-aws --build-arg CI_BUILD_URL=${CIRCLE_BUILD_URL} --build-arg GIT_COMMIT=${CIRCLE_SHA1} --build-arg GIT_REPO=${CIRCLE_REPOSITORY_URL} || exit 99
docker push rebar/rebar-graph-kubernetes || exit 99
docker push rebar/rebar-graph-aws || exit 99
docker logout 



