#!/bin/bash




build_image() {
    docker build rebar-graph-$1 \
    -t rebar/rebar-graph-$1 \
    --build-arg CI_BUILD_URL=${CIRCLE_BUILD_URL} \
    --build-arg GIT_COMMIT=${CIRCLE_SHA1} \
    --build-arg GIT_REPO=${CIRCLE_REPOSITORY_URL} || exit 99
}
push_image() {
    docker push rebar/rebar-graph-$1 || exit 99
}

build_image docker
build_image kubernetes
build_image aws


if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
    echo "branch $CIRCLE_BRANCH is not master ... will not publish images"
    exit 0
fi

if [ ! "${DOCKER_PASSWORD}" = "" ]; then
    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
fi

push_image docker
push_image kubernetes
push_image aws

docker logout 



