#!/bin/bash


if [[ $DOCKER_REGISTRY_USERNAME ]]; then
    echo $DOCKER_REGISTRY_USERNAME | docker login --username robschoening+rebarci@gmail.com --password-stdin
fi

pwd

IMAGE_NAME=$(basename $(pwd))

echo $IMAGE_NAME
docker build . -t $IMAGE_NAME -t rebar/$IMAGE_NAME

#docker push rebar/$IMAGE_NAME
