#!/bin/bash

export GRAPH_URL=${GRAPH_URL-"bolt://localhost:7687"}

GRAPH_URL=$(echo $GRAPH_URL | sed 's/bolt/http/')

echo $GRAPH_URL
for COUNT in {0..60}
do
    curl --silent $GRAPH_URL
    if [ "$?" = "0" ]; then
        echo OK
        exit 0
    fi
    sleep 1
done

exit 0
