site_name: Rebar
#theme:
#  name: 'material'

nav:
    - Overview: index.md
    - Architecture: architecture.md
    - AWS: aws.md
    - Kubernetes: kubernetes.md
    - Digital Ocean: digitalocean.md
    - GitHub: github.md
    - FAQ: faq.md

markdown_extensions:
  - codehilite